# Generated by Django 5.1 on 2024-09-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='hello@gmail.com', max_length=20),
            preserve_default=False,
        ),
    ]
